### ISSUE TITLE
chore: Drop support for Python 3.6, check compatibility with Python 3.10

### ISSUE THREAD

**Issue by phanak-sap** [SAP/python-pyodata#190]
Python 3.6 reached EOL (no security fixes) in 23 Dec 2021 and there is no actual need to stay backward-compatible. The lowest python version or this package should now be 3.7.

- [x] Add Python 3.10 to build matrix - #185
- [x] Drop Python 3.6 from travis builds - #190
- [x] Update the setup.py ( pipy documentation), update readme - #190
- [x] consider lowest LXML version possible to support based on 3.6 drop, update travis and setup.py dependencies accordingly - #190

**Comment by phanak-sap** [comment]
all done, in 1.8.0
